apiVersion: v1
kind: Pod
metadata: 
 name: mavenwebapppod
 labels: 
  app: mavenwebapp
spec:
  containers:
  - name: mavenwebappcontainer
    image: sumandevops1/maven-web-application:1
    ports:
    - containerPort: 8080
